"""Add automatic uuids

Revision ID: 0713e1092255
Revises: d8651f38a0c3
Create Date: 2025-07-02 16:29:26.016112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = '0713e1092255'
down_revision = 'd8651f38a0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
