"""Add Carcass

Revision ID: 07a60d00eb88
Revises: 9ab9daa9fa52
Create Date: 2025-07-19 00:34:17.102827

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = '07a60d00eb88'
down_revision = '9ab9daa9fa52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carcass',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('simulation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('world_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x_coord', sa.Integer(), nullable=False),
    sa.Column('y_coord', sa.Integer(), nullable=False),
    sa.Column('decay_time', sa.Integer(), nullable=False),
    sa.Column('energy_yield', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carcass')
    # ### end Alembic commands ###
