"""add memory to agent

Revision ID: 2d59102c584b
Revises: ad169b99b7a8
Create Date: 2025-07-06 16:47:38.013764

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = '2d59102c584b'
down_revision = 'ad169b99b7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actionlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('agent', 'memory')
    op.drop_column('agent', 'last_action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('last_action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agent', sa.Column('memory', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('actionlog')
    # ### end Alembic commands ###
