"""add action log

Revision ID: 3755545ac6cc
Revises: ad169b99b7a8
Create Date: 2025-07-06 20:18:23.534886

"""

import sqlalchemy as sa
import sqlmodel  # New
from alembic import op

# revision identifiers, used by Alembic.
revision = "3755545ac6cc"
down_revision = "ad169b99b7a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actionlog",
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("simulation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_actionlog_simulation_id"), "actionlog", ["simulation_id"], unique=False
    )
    op.drop_column("agent", "last_action")
    op.add_column(
        "configuration",
        sa.Column("last_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "simulation",
        sa.Column("last_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation", "last_used")
    op.drop_column("configuration", "last_used")
    op.add_column(
        "agent",
        sa.Column("last_action", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_actionlog_simulation_id"), table_name="actionlog")
    op.drop_table("actionlog")
    # ### end Alembic commands ###
