"""add_agent_death_and_carcass

Revision ID: 3f3e962b5e5b
Revises: 50830ba94924
Create Date: 2025-07-22 14:06:13.073565

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = '3f3e962b5e5b'
down_revision = '50830ba94924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
