"""add feedback to action log

Revision ID: 824ef4fb8a49
Revises: a9d85c763f61
Create Date: 2025-07-07 20:11:55.165734

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = '824ef4fb8a49'
down_revision = 'a9d85c763f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionlog', sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actionlog', 'feedback')
    # ### end Alembic commands ###
