"""Last Used Config

Revision ID: 960d087f10c1
Revises: c3b2e1d0f9a8
Create Date: 2025-07-06 14:39:46.081237

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = '960d087f10c1'
down_revision = 'c3b2e1d0f9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('last_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'last_used')
    # ### end Alembic commands ###
