"""add personality to agent

Revision ID: 9ab9daa9fa52
Revises: af81e5b9a3f3
Create Date: 2025-07-09 18:20:26.468358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = '9ab9daa9fa52'
down_revision = 'af81e5b9a3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('personality', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'personality')
    # ### end Alembic commands ###
