"""Add x,y to world

Revision ID: 9be9e3634bb6
Revises: 0713e1092255
Create Date: 2025-07-02 16:52:18.851649

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = '9be9e3634bb6'
down_revision = '0713e1092255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('world', sa.Column('size_x', sa.Integer(), nullable=False))
    op.add_column('world', sa.Column('size_y', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('world', 'size_y')
    op.drop_column('world', 'size_x')
    # ### end Alembic commands ###
