"""add conversation properties

Revision ID: a9d85c763f61
Revises: bc1aefe96386
Create Date: 2025-07-07 15:16:36.366730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = 'a9d85c763f61'
down_revision = 'bc1aefe96386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('declined', sa.Boolean(), nullable=False))
    op.add_column('conversation', sa.Column('finished', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'finished')
    op.drop_column('conversation', 'declined')
    # ### end Alembic commands ###
