"""add_foregin_keys

Revision ID: ad169b99b7a8
Revises: b51835aeed6c
Create Date: 2025-07-04 23:43:11.048632

"""

import sqlalchemy as sa
import sqlmodel  # New
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad169b99b7a8"
down_revision = "b51835aeed6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "agent", "plan", ["participating_in_plan_id"], ["id"])
    op.create_foreign_key(None, "agent", "simulation", ["simulation_id"], ["id"])
    op.create_foreign_key(None, "agent", "resource", ["harvesting_resource_id"], ["id"])
    op.create_foreign_key(None, "conversation", "agent", ["agent_b_id"], ["id"])
    op.create_foreign_key(None, "conversation", "agent", ["agent_a_id"], ["id"])
    op.create_foreign_key(None, "conversation", "simulation", ["simulation_id"], ["id"])
    op.create_foreign_key(None, "message", "agent", ["agent_id"], ["id"])
    op.create_foreign_key(None, "message", "conversation", ["conversation_id"], ["id"])
    op.create_foreign_key(None, "plan", "agent", ["owner_id"], ["id"])
    op.create_foreign_key(None, "region", "world", ["world_id"], ["id"])
    op.create_foreign_key(None, "region", "simulation", ["simulation_id"], ["id"])
    op.create_foreign_key(None, "relationship", "agent", ["agent_b_id"], ["id"])
    op.create_foreign_key(None, "relationship", "agent", ["agent_a_id"], ["id"])
    op.create_foreign_key(None, "resource", "world", ["world_id"], ["id"])
    op.create_foreign_key(None, "resource", "simulation", ["simulation_id"], ["id"])
    op.create_foreign_key(None, "resource", "region", ["region_id"], ["id"])
    op.create_foreign_key(None, "task", "resource", ["target_id"], ["id"])
    op.create_foreign_key(None, "task", "agent", ["worker_id"], ["id"])
    op.create_foreign_key(None, "task", "plan", ["plan_id"], ["id"])
    op.create_foreign_key(None, "world", "simulation", ["simulation_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "world", type_="foreignkey")
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_constraint(None, "resource", type_="foreignkey")
    op.drop_constraint(None, "resource", type_="foreignkey")
    op.drop_constraint(None, "resource", type_="foreignkey")
    op.drop_constraint(None, "relationship", type_="foreignkey")
    op.drop_constraint(None, "relationship", type_="foreignkey")
    op.drop_constraint(None, "region", type_="foreignkey")
    op.drop_constraint(None, "region", type_="foreignkey")
    op.drop_constraint(None, "plan", type_="foreignkey")
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_constraint(None, "conversation", type_="foreignkey")
    op.drop_constraint(None, "conversation", type_="foreignkey")
    op.drop_constraint(None, "conversation", type_="foreignkey")
    op.drop_constraint(None, "agent", type_="foreignkey")
    op.drop_constraint(None, "agent", type_="foreignkey")
    op.drop_constraint(None, "agent", type_="foreignkey")
    # ### end Alembic commands ###
