"""Relationships

Revision ID: bc1aefe96386
Revises: 3755545ac6cc
Create Date: 2025-07-06 22:36:35.191248

"""

import sqlalchemy as sa
import sqlmodel  # New
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc1aefe96386"
down_revision = "3755545ac6cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "relationship",
        sa.Column("simulation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("relationship", sa.Column("tick", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_relationship_simulation_id"),
        "relationship",
        ["simulation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relationship_tick"), "relationship", ["tick"], unique=False
    )
    op.create_foreign_key(None, "relationship", "simulation", ["simulation_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "relationship", type_="foreignkey")
    op.drop_index(op.f("ix_relationship_tick"), table_name="relationship")
    op.drop_index(op.f("ix_relationship_simulation_id"), table_name="relationship")
    op.drop_column("relationship", "tick")
    op.drop_column("relationship", "simulation_id")
    # ### end Alembic commands ###
