"""split_decision

Revision ID: e5342a04c60a
Revises: 9ab9daa9fa52
Create Date: 2025-07-11 02:03:54.125402

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                                 # New


# revision identifiers, used by Alembic.
revision = 'e5342a04c60a'
down_revision = '9ab9daa9fa52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('harvest_decisions', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'harvest_decisions')
    # ### end Alembic commands ###
