"""remove being_harvested

Revision ID: f7276b3fdcbb
Revises: 824ef4fb8a49
Create Date: 2025-07-07 23:48:54.752755

"""

import sqlalchemy as sa
import sqlmodel  # New
from alembic import op

# revision identifiers, used by Alembic.
revision = "f7276b3fdcbb"
down_revision = "824ef4fb8a49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource", "being_harvested")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource",
        sa.Column("being_harvested", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
